// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace bm.DeskSharing.Models;

public partial class Building
{
    public long BID { get; set; }

    public string BCode { get; set; }

    public string BName { get; set; }

    public string BDesc { get; set; }

    public DateTime tsCreated { get; set; }

    public DateTime tsModify { get; set; }

    public string sUser { get; set; }

    public bool? isActive { get; set; }

    public virtual ICollection<Floor> Floors { get; } = new List<Floor>();
}